version: '3.8'


services:
  app_blue:
    image: "${BLUE_IMAGE}"
    container_name: app_blue    
    environment:
      - PORT=${PORT}
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      
    ports:
      - "8081:3000"
    restart: always


  app_green:
    image: "${GREEN_IMAGE}"
    container_name: app_green
    environment:
      - PORT=${PORT}
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      
    ports:
      - "8082:3000"
    restart: always


  nginx:
    image: nginx:latest
    
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.template.conf:/etc/nginx/templates/nginx.template.conf:ro
      - ./nginx_logs:/var/log/nginx
    env_file:
      - .env
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL} 
    command: /bin/sh -c "envsubst '\$ACTIVE_POOL' < /etc/nginx/templates/nginx.template.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"   
    depends_on:
      - app_blue
      - app_green 
    restart: always


  alert_watcher:
    image: python:3.12-slim
    container_name: alert_watcher
    volumes:
      - ./nginx_logs:/var/log/nginx
      - ./watcher/watcher.py:/watcher/watcher.py:ro
      - ./watcher/requirements.txt:/watcher/requirements.txt:ro
      - ./watcher/data:/watcher/data  # host folder for maintenance flag
    working_dir: /watcher
    env_file:
      - .env
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD:-2}
      - WINDOW_SIZE=${WINDOW_SIZE:-200}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC:-300}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - MAINTENANCE_FILE=/watcher/data/maintenance_mode
    command: bash -c "pip install -r requirements.txt && python watcher.py"
    depends_on:
      - nginx

volumes:
  nginx_logs:
  watcher_data:
